export const en = {
  common: { appName: 'Khan-BMS', loading: 'Loading...', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', add: 'Add', search: 'Search', filter: 'Filter', export: 'Export', print: 'Print', yes: 'Yes', no: 'No', confirm: 'Confirm', success: 'Success', error: 'Error', warning: 'Warning', info: 'Information', currency: 'PKR' },
  auth: { login: 'Login', logout: 'Logout', register: 'Register', email: 'Email', password: 'Password', businessName: 'Business Name', phone: 'Phone Number', signIn: 'Sign In', signUp: 'Sign Up', dontHaveAccount: "Don't have an account?", alreadyHaveAccount: 'Already have an account?', forgotPassword: 'Forgot Password?' },
  nav: { dashboard: 'Dashboard', products: 'Products', sales: 'Sales', inventory: 'Inventory', reports: 'Reports', expenses: 'Expenses', settings: 'Settings', subscription: 'Subscription', admin: 'Admin Panel' },
  dashboard: { title: 'Dashboard', todaySales: "Today's Sales", weeklySales: 'Weekly Sales', monthlySales: 'Monthly Sales', totalProfit: 'Total Profit', totalLoss: 'Total Loss', lowStock: 'Low Stock Items', topProducts: 'Top Selling Products', recentTransactions: 'Recent Transactions', quickStats: 'Quick Statistics' },
  products: { title: 'Products', addProduct: 'Add Product', editProduct: 'Edit Product', productName: 'Product Name', purchasePrice: 'Purchase Price', sellingPrice: 'Selling Price', quantity: 'Quantity', unit: 'Unit', category: 'Category', supplier: 'Supplier', lowStockThreshold: 'Low Stock Alert', image: 'Image', nameInEnglish: 'Name (English)', nameInUrdu: 'Name (Urdu)', nameInPashto: 'Name (Pashto)', stockStatus: 'Stock Status', inStock: 'In Stock', lowStockAlert: 'Low Stock', outOfStock: 'Out of Stock', profitMargin: 'Profit Margin' },
  sales: { title: 'Sales', newSale: 'New Sale', saleHistory: 'Sale History', addItem: 'Add Item', selectProduct: 'Select Product', quantity: 'Quantity', unitPrice: 'Unit Price', subtotal: 'Subtotal', total: 'Total', profit: 'Profit', paymentMethod: 'Payment Method', cash: 'Cash', card: 'Card', online: 'Online', customerName: 'Customer Name', customerPhone: 'Customer Phone', receiptNumber: 'Receipt Number', generateReceipt: 'Generate Receipt' },
  reports: { title: 'Reports & Analytics', dailyReport: 'Daily Report', weeklyReport: 'Weekly Report', monthlyReport: 'Monthly Report', customRange: 'Custom Date Range', salesTrends: 'Sales Trends', productPerformance: 'Product Performance', profitAnalysis: 'Profit Analysis', exportPDF: 'Export as PDF', exportExcel: 'Export as Excel', bestSellers: 'Best Sellers', worstSellers: 'Worst Sellers', revenue: 'Revenue' },
  expenses: { title: 'Expenses', addExpense: 'Add Expense', description: 'Description', amount: 'Amount', category: 'Category', date: 'Date', notes: 'Notes', totalExpenses: 'Total Expenses' },
  subscription: { title: 'Subscription', currentPlan: 'Current Plan', free: 'Free Demo', standard: 'Standard', premium: 'Premium', upgrade: 'Upgrade', features: 'Features', expiresOn: 'Expires On', applyCoupon: 'Apply Coupon', couponCode: 'Coupon Code', discount: 'Discount', standardPrice: '200 PKR/month', premiumPrice: '500 PKR/month', freeFeatures: 'Limited features, 10 products max, 7-day analytics', standardFeatures: 'Full dashboard, 500 products, daily/weekly/monthly analytics', premiumFeatures: 'Unlimited products, advanced analytics, multi-branch, SMS/Email' },
  settings: { title: 'Settings', profile: 'Profile', language: 'Language', businessSettings: 'Business Settings', notifications: 'Notifications', security: 'Security', businessType: 'Business Type', saveChanges: 'Save Changes' },
  admin: { title: 'Admin Panel', users: 'All Users', statistics: 'System Statistics', coupons: 'Manage Coupons', totalUsers: 'Total Users', totalRevenue: 'Total Revenue', activeSubscriptions: 'Active Subscriptions', createCoupon: 'Create Coupon', usageLimit: 'Usage Limit', expiryDate: 'Expiry Date' },
  messages: { loginSuccess: 'Login successful', logoutSuccess: 'Logged out successfully', registerSuccess: 'Registration successful', productAdded: 'Product added successfully', productUpdated: 'Product updated successfully', productDeleted: 'Product deleted successfully', saleRecorded: 'Sale recorded successfully', expenseAdded: 'Expense added successfully', profileUpdated: 'Profile updated successfully', errorOccurred: 'An error occurred', invalidCoupon: 'Invalid or expired coupon code', couponApplied: 'Coupon applied successfully' },
} as const;

export type TranslationKeys = typeof en;
