import type { TranslationKeys } from './en';

export const ps: TranslationKeys = {
  common: { appName: 'خان-BMS', loading: 'لوډ کیږي...', save: 'خوندي کړئ', cancel: 'لغوه کړئ', delete: 'حذف کړئ', edit: 'سمون کړئ', add: 'اضافه کړئ', search: 'لټون', filter: 'فلټر', export: 'صادرول', print: 'چاپ کړئ', yes: 'هو', no: 'نه', confirm: 'تصدیق کړئ', success: 'بریالیتوب', error: 'تېروتنه', warning: 'خبرداری', info: 'معلومات', currency: 'روپۍ' },
  auth: { login: 'ننوتل', logout: 'وتل', register: 'ثبت کړئ', email: 'ایمیل', password: 'پاسورډ', businessName: 'سوداګرۍ نوم', phone: 'ټیلیفون شمیره', signIn: 'ننوتل', signUp: 'ثبت نام', dontHaveAccount: 'حساب نلرئ؟', alreadyHaveAccount: 'دمخه حساب لرئ؟', forgotPassword: 'پاسورډ هیر شوی؟' },
  nav: { dashboard: 'ډشبورډ', products: 'محصولات', sales: 'پلورنه', inventory: 'انوینټري', reports: 'راپورونه', expenses: 'لګښتونه', settings: 'ترتیبات', subscription: 'ګډون', admin: 'اډمین پینل' },
  dashboard: { title: 'ډشبورډ', todaySales: 'نن ورځې پلور', weeklySales: 'اونیزه پلور', monthlySales: 'میاشتنۍ پلور', totalProfit: 'ټوله ګټه', totalLoss: 'ټوله زیان', lowStock: 'کم سټاک توکي', topProducts: 'غوره پلورل شوي محصولات', recentTransactions: 'وروستي معاملې', quickStats: 'چټک احصائیې' },
  products: { title: 'محصولات', addProduct: 'محصول اضافه کړئ', editProduct: 'محصول سمون کړئ', productName: 'محصول نوم', purchasePrice: 'پیرود بیه', sellingPrice: 'پلور بیه', quantity: 'مقدار', unit: 'واحد', category: 'کټګورۍ', supplier: 'عرضه کوونکی', lowStockThreshold: 'کم سټاک خبرتیا', image: 'انځور', nameInEnglish: 'نوم (انګلیسي)', nameInUrdu: 'نوم (اردو)', nameInPashto: 'نوم (پښتو)', stockStatus: 'سټاک حالت', inStock: 'په سټاک کې', lowStockAlert: 'کم سټاک', outOfStock: 'سټاک ختم', profitMargin: 'ګټې مارجن' },
  sales: { title: 'پلورنه', newSale: 'نوې پلورنه', saleHistory: 'د پلور تاریخ', addItem: 'توکی اضافه کړئ', selectProduct: 'محصول غوره کړئ', quantity: 'مقدار', unitPrice: 'واحد بیه', subtotal: 'فرعي مجموعه', total: 'ټول', profit: 'ګټه', paymentMethod: 'د تادیې طریقه', cash: 'نقد', card: 'کارډ', online: 'آنلاین', customerName: 'پیرودونکي نوم', customerPhone: 'پیرودونکي ټیلیفون', receiptNumber: 'رسید شمیره', generateReceipt: 'رسید تولید کړئ' },
  reports: { title: 'راپورونه او تحلیل', dailyReport: 'ورځني راپور', weeklyReport: 'اونیز راپور', monthlyReport: 'میاشتني راپور', customRange: 'دوره ای نیټه حد', salesTrends: 'د پلور رجحانات', productPerformance: 'د محصول کارکرد', profitAnalysis: 'د ګټې تحلیل', exportPDF: 'د PDF په توګه صادرول', exportExcel: 'د Excel په توګه صادرول', bestSellers: 'غوره پلورونکي', worstSellers: 'کم پلورونکي', revenue: 'عاید' },
  expenses: { title: 'لګښتونه', addExpense: 'لګښت اضافه کړئ', description: 'تفصیل', amount: 'مقدار', category: 'کټګورۍ', date: 'نیټه', notes: 'یادښتونه', totalExpenses: 'ټول لګښتونه' },
  subscription: { title: 'ګډون', currentPlan: 'اوسنۍ پلان', free: 'وړیا ډیمو', standard: 'معیاري', premium: 'پریمیم', upgrade: 'لوړول', features: 'ځانګړتیاوې', expiresOn: 'پای نیټه', applyCoupon: 'کوپن ولګوئ', couponCode: 'کوپن کوډ', discount: 'تخفیف', standardPrice: '200 روپۍ/میاشت', premiumPrice: '500 روپۍ/میاشت', freeFeatures: 'محدود ځانګړتیاوې، 10 محصولات، 7 ورځې تحلیل', standardFeatures: 'بشپړ ډشبورډ، 500 محصولات، ورځني/اونیز/میاشتني تحلیل', premiumFeatures: 'لامحدوده محصولات، پرمختللې تحلیلونه، ملټي برانچ، SMS/ایمیل' },
  settings: { title: 'ترتیبات', profile: 'پروفایل', language: 'ژبه', businessSettings: 'سوداګرۍ ترتیبات', notifications: 'خبرتیاوې', security: 'امنیت', businessType: 'سوداګرۍ ډول', saveChanges: 'بدلونونه خوندي کړئ' },
  admin: { title: 'اډمین پینل', users: 'ټول کاروونکي', statistics: 'سیسټم احصائیې', coupons: 'کوپن اداره کړئ', totalUsers: 'ټول کاروونکي', totalRevenue: 'ټول عاید', activeSubscriptions: 'فعال ګډون', createCoupon: 'کوپن جوړ کړئ', usageLimit: 'استعمال حد', expiryDate: 'پای نیټه' },
  messages: { loginSuccess: 'ننوتل بریالي', logoutSuccess: 'وتل بریالي', registerSuccess: 'ثبت نام بریالي', productAdded: 'محصول په بریالیتوب سره اضافه شو', productUpdated: 'محصول په بریالیتوب سره تازه شو', productDeleted: 'محصول په بریالیتوب سره حذف شو', saleRecorded: 'پلورنه په بریالیتوب سره ثبت شوه', expenseAdded: 'لګښت په بریالیتوب سره اضافه شو', profileUpdated: 'پروفایل په بریالیتوب سره تازه شو', errorOccurred: 'یوه تېروتنه رامنځته شوه', invalidCoupon: 'غلط یا پای ته رسیدلی کوپن کوډ', couponApplied: 'کوپن په بریالیتوب سره لګول شو' },
};
