import type { TranslationKeys } from './en';

export const ur: TranslationKeys = {
  common: { appName: 'خان-BMS', loading: 'لوڈ ہو رہا ہے...', save: 'محفوظ کریں', cancel: 'منسوخ کریں', delete: 'حذف کریں', edit: 'ترمیم کریں', add: 'شامل کریں', search: 'تلاش کریں', filter: 'فلٹر', export: 'ایکسپورٹ', print: 'پرنٹ کریں', yes: 'ہاں', no: 'نہیں', confirm: 'تصدیق کریں', success: 'کامیابی', error: 'خرابی', warning: 'انتباہ', info: 'معلومات', currency: 'روپے' },
  auth: { login: 'لاگ ان', logout: 'لاگ آؤٹ', register: 'رجسٹر کریں', email: 'ای میل', password: 'پاس ورڈ', businessName: 'کاروبار کا نام', phone: 'فون نمبر', signIn: 'سائن ان کریں', signUp: 'سائن اپ کریں', dontHaveAccount: 'اکاؤنٹ نہیں ہے؟', alreadyHaveAccount: 'پہلے سے اکاؤنٹ ہے؟', forgotPassword: 'پاس ورڈ بھول گئے؟' },
  nav: { dashboard: 'ڈیش بورڈ', products: 'مصنوعات', sales: 'فروخت', inventory: 'انوینٹری', reports: 'رپورٹس', expenses: 'اخراجات', settings: 'ترتیبات', subscription: 'سبسکرپشن', admin: 'ایڈمن پینل' },
  dashboard: { title: 'ڈیش بورڈ', todaySales: 'آج کی فروخت', weeklySales: 'ہفتہ وار فروخت', monthlySales: 'ماہانہ فروخت', totalProfit: 'کل منافع', totalLoss: 'کل نقصان', lowStock: 'کم اسٹاک اشیاء', topProducts: 'سب سے زیادہ فروخت ہونے والی مصنوعات', recentTransactions: 'حالیہ لین دین', quickStats: 'فوری اعدادوشمار' },
  products: { title: 'مصنوعات', addProduct: 'مصنوعات شامل کریں', editProduct: 'مصنوعات میں ترمیم کریں', productName: 'مصنوعات کا نام', purchasePrice: 'خریداری قیمت', sellingPrice: 'فروخت قیمت', quantity: 'مقدار', unit: 'یونٹ', category: 'زمرہ', supplier: 'سپلائر', lowStockThreshold: 'کم اسٹاک الرٹ', image: 'تصویر', nameInEnglish: 'نام (انگریزی)', nameInUrdu: 'نام (اردو)', nameInPashto: 'نام (پشتو)', stockStatus: 'اسٹاک کی حیثیت', inStock: 'اسٹاک میں', lowStockAlert: 'کم اسٹاک', outOfStock: 'اسٹاک ختم', profitMargin: 'منافع کا مارجن' },
  sales: { title: 'فروخت', newSale: 'نئی فروخت', saleHistory: 'فروخت کی تاریخ', addItem: 'شے شامل کریں', selectProduct: 'مصنوعات منتخب کریں', quantity: 'مقدار', unitPrice: 'یونٹ قیمت', subtotal: 'ذیلی کل', total: 'کل', profit: 'منافع', paymentMethod: 'ادائیگی کا طریقہ', cash: 'نقد', card: 'کارڈ', online: 'آن لائن', customerName: 'گاہک کا نام', customerPhone: 'گاہک کا فون', receiptNumber: 'رسید نمبر', generateReceipt: 'رسید بنائیں' },
  reports: { title: 'رپورٹس اور تجزیہ', dailyReport: 'روزانہ رپورٹ', weeklyReport: 'ہفتہ وار رپورٹ', monthlyReport: 'ماہانہ رپورٹ', customRange: 'حسب ضرورت تاریخ کی حد', salesTrends: 'فروخت کے رجحانات', productPerformance: 'مصنوعات کی کارکردگی', profitAnalysis: 'منافع کا تجزیہ', exportPDF: 'PDF کے طور پر ایکسپورٹ کریں', exportExcel: 'Excel کے طور پر ایکسپورٹ کریں', bestSellers: 'بہترین فروخت', worstSellers: 'کم فروخت', revenue: 'آمدنی' },
  expenses: { title: 'اخراجات', addExpense: 'اخراجات شامل کریں', description: 'تفصیل', amount: 'رقم', category: 'زمرہ', date: 'تاریخ', notes: 'نوٹس', totalExpenses: 'کل اخراجات' },
  subscription: { title: 'سبسکرپشن', currentPlan: 'موجودہ پلان', free: 'مفت ڈیمو', standard: 'معیاری', premium: 'پریمیم', upgrade: 'اپ گریڈ', features: 'خصوصیات', expiresOn: 'ختم ہونے کی تاریخ', applyCoupon: 'کوپن لگائیں', couponCode: 'کوپن کوڈ', discount: 'رعایت', standardPrice: '200 روپے/ماہ', premiumPrice: '500 روپے/ماہ', freeFeatures: 'محدود خصوصیات، 10 مصنوعات، 7 دن کے تجزیات', standardFeatures: 'مکمل ڈیش بورڈ، 500 مصنوعات، روزانہ/ہفتہ وار/ماہانہ تجزیات', premiumFeatures: 'لامحدود مصنوعات، جدید تجزیات، ملٹی برانچ، SMS/ای میل' },
  settings: { title: 'ترتیبات', profile: 'پروفائل', language: 'زبان', businessSettings: 'کاروبار کی ترتیبات', notifications: 'اطلاعات', security: 'سیکیورٹی', businessType: 'کاروبار کی قسم', saveChanges: 'تبدیلیاں محفوظ کریں' },
  admin: { title: 'ایڈمن پینل', users: 'تمام صارفین', statistics: 'سسٹم کے اعدادوشمار', coupons: 'کوپن کا نظم کریں', totalUsers: 'کل صارفین', totalRevenue: 'کل آمدنی', activeSubscriptions: 'فعال سبسکرپشنز', createCoupon: 'کوپن بنائیں', usageLimit: 'استعمال کی حد', expiryDate: 'ختم ہونے کی تاریخ' },
  messages: { loginSuccess: 'لاگ ان کامیاب', logoutSuccess: 'لاگ آؤٹ کامیاب', registerSuccess: 'رجسٹریشن کامیاب', productAdded: 'مصنوعات کامیابی سے شامل ہوگئی', productUpdated: 'مصنوعات کامیابی سے اپ ڈیٹ ہوگئی', productDeleted: 'مصنوعات کامیابی سے حذف ہوگئی', saleRecorded: 'فروخت کامیابی سے ریکارڈ ہوگئی', expenseAdded: 'اخراجات کامیابی سے شامل ہوگئے', profileUpdated: 'پروفائل کامیابی سے اپ ڈیٹ ہوا', errorOccurred: 'ایک خرابی واقع ہوئی', invalidCoupon: 'غلط یا میعاد ختم کوپن کوڈ', couponApplied: 'کوپن کامیابی سے لاگو ہوا' },
};
